hydra:
  run:
    dir: "./results/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}"

system_parameters:
  MODEL_NAME: "meta-llama/Llama-2-7b-hf"
  OUTPUT_DIR: "../results"
  DATASET_NAME: "../data/processed/GPT4_synthetic_data.json"
  NEW_DATASET_NAME: "luisroque/instruct-python-llama2-20k"
  NEW_DATASET_NAME_LOCAL: "instruct-python-500k.pkl"
  NEW_MODEL_PATH: "../models/Llama-2-7b-mini-eldercare-domain"
  NEW_MODEL_PATH_MERGE: "../models/Llama-2-7b-mini-eldercare-domain-merge"
  NEW_MODEL_NAME: "Llama-2-7b-mini-eldercare-domain"
  SYSTEM_MESSAGE: "
You are an AI expert in medicine and elder care, assisting a social or health care assistant or a nurse in documenting patient observations.
You receive input through voice conversations. Your task is to accurately transcribe the events as described by the user into the documentation.
Maintain the user's original wording, tense, and style, and correct only grammatical errors.
Avoid including small talk, irrelevant discussions, or personal opinions. When talking to the user, think step by step using this script:

1. Transcription Integrity: Update the documentation based on the events as described by the user.
Preserve the user's original wording, tense, and style, making adjustments only for grammatical accuracy.

Output in JSON format.
"

hyperparameters:
  NUM_EPOCHS: 1
  BATCH_SIZE: 2
  GRAD_ACC_STEPS: 1
  SAVE_STEPS: 50
  LOG_STEPS: 5
  LEARNING_RATE: 2e-4
  WEIGHT_DECAY: 0.001
  MAX_GRAD_NORM: 0.3
  SCHEDULER_TYPE: "cosine"
  PER_DEVICE_TRAIN_BATCH_SIZE: 4
  PER_DEVICE_EVAL_BATCH_SIZE: 4
  OPTIM: "paged_adamw_32bit"
  FP16: False
  BF16: False
  MAX_STEPS: 1000
  WARMUP_RATIO: 0.03
  GROUP_BY_LENGTH: 3
  LORA_ALPHA: 16
  LORA_DROPOUT: 0.1
  LORA_R: 64
  DEVICE_MAP: {"": 0}
  USE_4BIT: True
  BNB_4BIT_COMPUTE_DTYPE: "float16"
  BNB_4BIT_COMPUTE_QUANT_TYPE: "nf4"
  USE_NESTED_QUANT: False
